image:
  name: hasura/graphql-engine:v2.11.10
  pullPolicy: IfNotPresent
server:
  databaseURL: postgres://hasura:password@hasura-postgresql.default:5432/hasura
  console: true
  devMode: true
podLabels:
  app: hasura
  version: 2.11.10
service:
  port: 80
  type: ClusterIP
ingress:
  enabled: true
  annotations: {}
  ingressClassName: ""
  hostname: "hasura.localhost"
  path: /
  pathType: ImplementationSpecific
  servicePort: 80
  tls: false
postgresql:
  enabled: true
  auth:
    postgresPassword: password
    username: hasura
    password: password
    database: hasura
    replicationUsername: repl_hasura
    replicationPassword: password
  primary:
    podLabels:
      app: postgresql
      version: 15.4.0
  readReplicas:
    podLabels:
      app: postgresql
      version: 15.4.0
